# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c49c8e60e7361bcba5aff29006e1d94"
name = "Geo: Redirect & Country Block"
application_url = "https://geopro.bluepeaks.top"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://geopro.bluepeaks.top/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://geopro.bluepeaks.top/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "https://geopro.bluepeaks.top/webhooks/app/gdpr"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "https://geopro.bluepeaks.top/webhooks/app/gdpr"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "https://geopro.bluepeaks.top/webhooks/app/gdpr"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://geopro.bluepeaks.top/auth/callback",
  "https://geopro.bluepeaks.top/auth/shopify/callback"
]

# App Proxy - Provides stable URL for storefront extension API calls
[app_proxy]
url = "https://geopro.bluepeaks.top/proxy"
subpath = "geolocation"
prefix = "apps"

